### ISSUE TITLE
Modernize the Sass lessons

### ISSUE THREAD

**Issue by egillespie** [humanitycodes/codelab#314]
Sass has had some big updates recently that should be incorporated into the Sass lessons:

1. Switch from `node-sass` to Dart-sass
2. Introduce Sass modules before global functions are deprecated

Make sure to update the Sass introduction lesson and the package.json lesson.

Here are the commands for using Dart sass:

``` sh
#Install
npm install -g sass

#compile single file
sass style.scss style.css

#compile file to a different directory
sass source/scss/style.scss compiled/css/style.css

#compile minified file to a different directory
sass --style=compressed source/scss/style.scss compiled/css/style.css

#compile minified file with souce map to different directory
sass --style=compressed --embed-sources source/scss/style.scss compiled/css/style.css

#Automatically recompile files when changed
sass --watch --style=compressed --embed-sources [directory of input scss]:[directory of output css]
For example: sass --style=compressed --embed-sources --watch source/scss:compiled/css
```

**Tasks**

- [x] Sass Intro lesson: Switch from `node-sass` to Dart-sass
- [x] Sass Intro lesson: Introduce Sass modules
- [x] Sass Intro lesson: Require Sass module in project
- [x] package.json lesson: Switch from `node-sass` to Dart-sass
